language: node_js

cache:
  directories:
    - ~/.npm

notifications:
  email: false

node_js: '8'

script: npm start validate

after_success: npx codecov

deploy:
  provider: script
  skip_cleanup: true
  script: npx semantic-release

branches:
  except: /^v\d+\.\d+\.\d+$/
